In [2]:
from MySimpleLR import MySLR
import pandas as pd 

In [4]:
lr = MySLR()

In [5]:
df = pd.read_csv('datasets/IceCreamData.csv')
x = df.iloc[:,0].values.reshape(-1,1)
y = df.iloc[:,1].values.reshape(-1,1)

In [6]:
from sklearn .model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [8]:
x_test.shape

(100, 1)

In [9]:
lr.fit(x_train,y_train)

[21.5133908]
[43.73357869]


In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
sklr = LinearRegression()

In [12]:
sklr.fit(x_train,y_train)

LinearRegression()

In [13]:
sklr.coef_

array([[21.5133908]])

In [14]:
sklr.intercept_

array([43.73357869])

In [19]:
y_hat = lr.predict(x_test)
y_hat

array([[698.3385558 ],
       [653.32331149],
       [664.73027451],
       [450.5192845 ],
       [665.47469743],
       [441.36861407],
       [584.06540609],
       [623.82532723],
       [667.48717467],
       [468.72433832],
       [546.82733151],
       [443.41191785],
       [622.95162777],
       [377.64639971],
       [367.0607334 ],
       [945.67057977],
       [893.79551974],
       [694.45445099],
       [546.05047608],
       [420.58523672],
       [391.08500303],
       [597.0141581 ],
       [283.23582775],
       [655.50055011],
       [380.98796154],
       [412.31810124],
       [371.05055651],
       [510.23910289],
       [479.70270426],
       [456.68206658],
       [640.1157508 ],
       [281.65224383],
       [314.1894674 ],
       [470.01363777],
       [559.72453055],
       [539.75091165],
       [307.72368191],
       [508.65180339],
       [571.43237276],
       [732.25599161],
       [440.44010989],
       [494.39422767],
       [567.56536766],
       [443

In [22]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [23]:
mean_absolute_error(y_test,y_hat)

18.30321353010285

In [26]:
mse = mean_squared_error(y_test,y_hat)
mse

528.2150684519324

In [27]:
import numpy as np 
np.sqrt(mse)

22.98292993619248

In [28]:
from sklearn.metrics import r2_score

In [29]:
r2 = r2_score(y_test,y_hat)
r2

0.9837324255882577